version: "3"
services:
  quotes_app:
    build: .
    container_name: quotes
    user: ctf
    working_dir: /home/ctf
    entrypoint: /bin/sh -c "./ynetd -p 5153 /home/ctf/launch.sh"
    ports:
      - "5153:5153"
    read_only: true
